swagger: "2.0"
info:
  version: "0.0.1"
  title: Supplier Api
# during dev, should point to your local machine
host: localhost:2000
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  
  /recieve:
    # our controller name
    x-swagger-router-controller: supplier
    post:
      operationId: recieve
      parameters:
        - name: Recieve
          in: body
          required: true
          schema:
            $ref: "#/definitions/Recieve"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:

  Recieve:
    required:
      - Amount
      - Account
      - Record
      - Items
    properties:
      Amount:
        type: number
      Account:
        type: number
      Record:
        type: string
      Items:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            number:
              type: number
              
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        
  GeneralResponse:
    required:
      - message
    properties:
      message:
        type: string